EdgedesignCZ/phpqa

.phpqa.yml
README.md
composer.json
src/CodeAnalysisTasks.php
src/Config.php
src/Options.php
src/paths.php
tests/Config/.phpqa.yml
tests/Config/ConfigTest.php
tests/ConfigTest.php
tests/OptionsTest.php

Configuration

---

app/report/phpcs.xsl
app/report/phpmd.xsl

HTTP sources causes Mixed Content errors.

Fix Mixed Content errors in templates (load jQuery from HTTPS)

---

.gitattributes

https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production/

Add gitattributes - don't export tests and dev files

---

README.md
composer.json
composer.lock

Upgrade robo, pdepend, phpmd

---

README.md
src/CodeAnalysisTasks.php
src/RunningTool.php
src/Task/NonParallelExec.php
src/Task/ParallelExec.php
src/Task/TableSummary.php
tests/RunningToolTest.php

```
phpqa --output cli --tools phpcs:0,phpmd:0,phpcpd:0
```

Analyze exit code in CLI mode

---

.travis.yml
README.md
app/report/phpqa.html.twig
composer.json
composer.lock
src/CodeAnalysisTasks.php
src/IgnoredPaths.php
src/RunningTool.php
src/Task/TableSummary.php
tests/.travis/phpstan.neon
tests/IgnoredPathsTest.php

Support phpmetrics v2

---

.travis.yml

This is a Redo of PR #51 and PR #45. The recent repo/HHVM changes fix the existing problems with those PRs

[Fixed] Run on trusty beta container / Current HHVM

---

.phpqa.yml
README.md
app/report/phpqa.html.twig
src/CodeAnalysisTasks.php
src/RunningTool.php
tests/.travis/.phpqa.yml
tests/Config/ConfigTest.php
tests/Error/errors.xml
tests/RunningToolTest.php

Advanced phpcs configuration

---

composer.json

Twig 2 tested in [php 7.1](https://travis-ci.org/EdgedesignCZ/phpqa/jobs/225661128#L280)

Support Twig 2

---

phpqa
src/CodeAnalysisTasks.php

Closes https://github.com/EdgedesignCZ/phpqa/issues/64

Support phpcs v3.X

---

README.md
bin/ci.sh
tests/.travis/.phpqa.yml

phpstan v0.7

---

composer.json

* https://getcomposer.org/doc/articles/versions.md
* https://semver.mwl.be/#?package=consolidation%2Frobo&version=~0%7C~1&minimum-stability=stable
* https://semver.mwl.be/#?package=twig%2Ftwig&version=~1%7C~2&minimum-stability=stable

Composer - fix version constrains (robo, twig), add php-cs-fixer to suggested tools

---

app/report/phpqa.html.twig
phpqa
src/CodeAnalysisTasks.php
src/Task/TableSummary.php
src/Task/ToolSummary.php
src/Task/ToolVersions.php

Just like in [CLI summary](https://github.com/EdgedesignCZ/phpqa#exit-code)
Demo at https://edgedesigncz.github.io/phpqa/report/phpqa.html

Summary dashboard in html report

---

.phpqa.yml
README.md
bin/ci.sh
bin/suggested-tools.sh
composer.json
src/Tools/Analyzer/SecurityChecker.php
tests/Config/ConfigTest.php

https://github.com/sensiolabs/security-checker

Support security-checker

---

.phpqa.yml
README.md
app/report/cli.html.twig
app/report/pdepend.xsl
app/report/php-cs-fixer.xsl
app/report/phpcpd.xsl
app/report/phpcs.xsl
app/report/phploc.xsl
app/report/phpmd.xsl
app/report/phpqa.html.twig
app/report/psalm.xsl
src/CodeAnalysisTasks.php
src/Options.php
src/Task/AssetsLoader.php
src/Tools/Tools.php
tests/.travis/psalm.xml
tests/Report/ReportTest.php

Closes https://github.com/EdgedesignCZ/phpqa/issues/95

Download assets if --report=offline

---

.travis.yml
bin/ci.sh
src/Tools/Tool.php
tests/.travis/psalm.xml

vimeo/psalm vs Symfony 4 
https://travis-ci.org/EdgedesignCZ/phpqa/jobs/322215928

CI - fix installing composer dependencies in PHP 7.1

---

.travis.yml
bin/suggested-tools.sh

Docker build error
https://travis-ci.org/EdgedesignCZ/phpqa/jobs/337159089#L1161
Similar composer issue
https://github.com/EdgedesignCZ/phpqa/pull/99/commits/d0c1220adf0fcee2c061548f3e27882e5bd419b5
Don't remove phpunit in 7.0 build
https://travis-ci.org/EdgedesignCZ/phpqa/jobs/337163813

CI - fix installing suggested tools in docker build

---

.phpqa.yml
README.md
app/report/phpstan.xsl
src/CodeAnalysisTasks.php
src/Tools/Analyzer/Phpstan.php

Closes https://github.com/EdgedesignCZ/phpqa/issues/108

phpstan - checkstyle, pretty html report

---

app/report/phpqa.html.twig

phpmetrics - fix menu in v2

---

src/Tools/Analyzer/Phpcs.php

https://github.com/EdgedesignCZ/phpqa/issues/119

phpcs - ignore warnings in cli mode

---

.travis.yml
bin/suggested-tools.sh

v2 causes failed builds
https://travis-ci.org/EdgedesignCZ/phpqa/jobs/381003238#L603
https://travis-ci.org/EdgedesignCZ/phpqa/jobs/381003239#L739
v2 released 7 days ago
https://github.com/vimeo/psalm/releases/tag/2.0.0
https://github.com/EdgedesignCZ/phpqa/pull/132/commits/5cf028a943408ece3b1ccd0ecc8e72c3682bd0a9

CI - install psalm v1, fix hhvm build

---

bin/suggested-tools.sh

Don't need latest version for Travis.
BC in 0.10 (https://github.com/phpstan/phpstan/releases/tag/0.10)
https://travis-ci.org/EdgedesignCZ/phpqa/jobs/397310631#L770

CI - fix installing phpstan (BC in 0.10)

---

src/Tools/Analyzer/Phpunit.php

* https://github.com/EdgedesignCZ/phpqa/issues/136
* https://github.com/EdgedesignCZ/phpqa/issues/137

Fix phpunit issues (escaped configuration path, html/xml coverage directory)

---

src/IgnoredPaths.php
tests/IgnoredPathsTest.php

Closes https://github.com/EdgedesignCZ/phpqa/issues/140.
[v1.13](https://github.com/EdgedesignCZ/phpqa/pull/81)

Fix ignoring subdirectories on Windows

---

src/IgnoredPaths.php
tests/IgnoredPathsTest.php

phpmd - fix excluding files on Windows

---

src/Tools/Analyzer/Phpstan.php
src/Tools/GetVersions.php

Related: https://github.com/EdgedesignCZ/phpqa/issues/150, https://github.com/EdgedesignCZ/phpqa/pull/152

phpstan - use --errorFormat only if version < 0.10.3

---

.travis.yml
README.md
appveyor.yml
src/Options.php
src/paths.php
tests/.appveyor/.phpqa.yml
tests/Config/ConfigTest.php
tests/OptionsTest.php

Closes https://github.com/EdgedesignCZ/phpqa/issues/141

CI - Windows build on Appveyor

---

src/Tools/Analyzer/Psalm.php
src/Tools/Analyzer/SecurityChecker.php
src/Tools/Tools.php

https://github.com/EdgedesignCZ/phpqa/commit/c4c3004
https://github.com/EdgedesignCZ/phpqa/pull/157

Tools - internalClass refactoring

---

.travis.yml
composer.json
composer.lock
src/Tools/Analyzer/SecurityChecker.php

Closes https://github.com/EdgedesignCZ/phpqa/issues/162

Travis - fix security-checker, drop hhvm

---

.docker/build-image
.travis.yml
bin/suggested-tools.sh

* v1.22 error - https://github.com/EdgedesignCZ/phpqa/commit/1fe23e7b
* v1.21 error - https://github.com/EdgedesignCZ/phpqa/commit/6ef3519
https://travis-ci.org/EdgedesignCZ/phpqa/jobs/558464512#L2025
```
Problem 1
- Conclusion: don't install sensiolabs/security-checker v6.0.1
- Conclusion: remove symfony/polyfill-mbstring v1.1.1
```

Fix docker build, always build docker image, publish it only for a git tag

---

src/Tools/Analyzer/Phpcpd.php

Fixes https://github.com/EdgedesignCZ/phpqa/issues/170
https://github.com/EdgedesignCZ/phpqa/pull/192

phpcpd - add extensions configuration (--names option)

---

src/RunningTool.php
src/Tools/Analyzer/Phpstan.php
src/Tools/GetVersions.php
tests/OptionsTest.php

Closes https://github.com/EdgedesignCZ/phpqa/issues/196

phpstan - require neon dependency

---

CHANGELOG.md
LICENSE
README.md
bin/deploy-report.sh
phpqa

Update docs for release 1.24.0

---

composer.json
composer.lock

Closes https://github.com/EdgedesignCZ/phpqa/issues/226
Related: [robo v1](https://github.com/EdgedesignCZ/phpqa/commit/1724025), [robo v2](https://github.com/EdgedesignCZ/phpqa/commit/148151cd)

Tools - enable installing new robo versions (>= 3)

---

.phpqa.yml
README.md
bin/suggested-tools.sh
composer.json
src/CodeAnalysisTasks.php
src/Tools/Analyzer/Deptrac.php
tests/.ci/.phpqa.yml
tests/.ci/depfile.yaml
tests/Config/ConfigTest.php

Closes https://github.com/EdgedesignCZ/phpqa/issues/229

Add deptrac

---

composer.lock
tests/.appveyor/.phpqa.yml
tests/.ci/.phpqa.yml
tests/.ci/phpmd.xml

Upgrade tools

---

.docker/Dockerfile
.docker/build-image
.github/workflows/docker.yml
CHANGELOG.md
README.md
phpqa

Docker - php 8.1, github container registry

---

.phpqa.yml
README.md
src/Tools/Analyzer/Deptrac.php

Closes https://github.com/EdgedesignCZ/phpqa/issues/258
_(migration to new deptrac version in https://github.com/EdgedesignCZ/phpqa/pull/265/commits/2a2079281a9b0d0b8252f79e7d7b10fc88659a36)_

Deptrac - add config for uncovered dependencies report

---

appveyor.yml
tests/.appveyor/.phpqa.yml

CI - update appveyor
